"""add owner propertieswhen showing a product to the user

Revision ID: 09dd96c2f873
Revises: d7bd6da6c5c1
Create Date: 2023-06-07 11:33:25.007151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09dd96c2f873'
down_revision = 'd7bd6da6c5c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
