"""adding votes table

Revision ID: 55f8c8562ead
Revises: 09dd96c2f873
Create Date: 2023-06-09 01:47:53.445161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f8c8562ead'
down_revision = '09dd96c2f873'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
