"""add product_owner_id column to products table

Revision ID: d7bd6da6c5c1
Revises: 1976fb79e402
Create Date: 2023-06-07 11:31:32.310242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7bd6da6c5c1'
down_revision = '1976fb79e402'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'users', ['product_owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'product_owner_id')
    # ### end Alembic commands ###
